IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Teachers')
BEGIN
   CREATE TABLE Teachers
   (
       Id INT PRIMARY KEY IDENTITY(1,1),
       FirstName NVARCHAR(50) NOT NULL,
       LastName NVARCHAR(50) NOT NULL,
       CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
       UpdatedAt DATETIME NOT NULL DEFAULT GETDATE()
   )
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Students')
BEGIN
   CREATE TABLE Students
   (
       Id INT PRIMARY KEY IDENTITY(1,1),
       FirstName NVARCHAR(50) NOT NULL,
       LastName NVARCHAR(50) NOT NULL,
       CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
       UpdatedAt DATETIME NOT NULL DEFAULT GETDATE()
   )
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Classes')
BEGIN
   CREATE TABLE Classes
   (
       Id INT PRIMARY KEY IDENTITY(1,1),
       TeacherId INT FOREIGN KEY REFERENCES Teachers(Id),
       CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
       UpdatedAt DATETIME NOT NULL DEFAULT GETDATE()
   )
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Grades')
BEGIN
   CREATE TABLE Grades
   (
       Id INT PRIMARY KEY IDENTITY(1,1),
       StudentId INT FOREIGN KEY REFERENCES Students(Id),
       ClassId INT FOREIGN KEY REFERENCES Classes(Id),
       Value FLOAT NOT NULL,
       CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
       UpdatedAt DATETIME NOT NULL DEFAULT GETDATE()
   )
END
